--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer
GROUP BY gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount?

-- finding average 
Select AVG(purchase_amount) from customer;--59.7643589743589744
--now checking if discount_applied and purchase >= avg 

select customer_id,purchase_amount from customer 
where discount_applied= 'Yes' and 
purchase_amount>=(Select AVG(purchase_amount) from customer);



--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased , ROUND(AVG(review_rating::Numeric),2) AS "average Product rating" from customer 
group by item_purchased 
order by AVG(review_rating) desc
limit 5;
-- rating is having double precision with more decimals 
--so we'll typecast it as numeric with 2 decimal points



--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type ,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard' , 'Express Shipping')
group by shipping_type;
--TO round off to 2 decimal points 



--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status , count(customer_id) AS total_customers ,
ROUND(AVG(purchase_amount),2) AS average_spend ,
ROUND(SUM(purchase_amount),2) AS total_revenue 
from customer
group by subscription_status 
order by total_revenue , average_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100.0 * SUM(CASE  WHEN (discount_applied) = 'Yes' THEN 1  ELSE 0 END ) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
--Q7. Segment customers into New, Returning, and Loyal based on their 
--total number of previous purchases, and show the count of each segment.

with customer_type as(
select customer_id , previous_purchases ,
CASE
  WHEN previous_purchases=1 then 'NEW'
  when previous_purchases between 2 and 10 then 'RETURNING'
  else 'LOYAL'
END as customer_segment
from customer
)
select customer_segment , count(*) as "no of customers" from customer_type
group by customer_segment;
--Q8. What are the top 3 most purchased products within each category?

WITH items_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
	category,
    item_purchased,
    total_orders
FROM items_count
WHERE item_rank <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) 
--also likely to subscribe?
select subscription_status , count(customer_id) as repeat_buyers
from customer
where previous_purchases >5 
group by subscription_status;

--Q10. What is the revenue contribution of each age group?
select age_group,SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;



SELECT COUNT(*) FROM customer;